sudo: required
services:
  - docker

before_install:
  - docker build -t gerdreiss/frontend -f frontend/Dockerfile.dev frontend
#  - docker build -t gerdreiss/complex/client -f complex/client/Dockerfile.dev complex/client
#  - docker build -t gerdreiss/complex/server -f complex/server/Dockerfile.dev complex/server
#  - docker build -t gerdreiss/complex/worker -f complex/worker/Dockerfile.dev complex/worker

script:
  - docker run gerdreiss/frontend npm run test -- --coverage
#  - docker run gerdreiss/complex/client npm run test -- --coverage
#  - docker run gerdreiss/complex/server npm run test -- --coverage
#  - docker run gerdreiss/complex/worker npm run test -- --coverage
