sudo: required
services:
  - docker

before_install:
  - docker build -t gerdreiss/docker-react -f frontend/Dockerfile.dev frontend

script:
  - docker run gerdreiss/docker-react npm run test -- --coverage