FROM alpine

RUN export http_proxy=http://proxy.olymp:3128 \
 && export https_proxy=http://proxy.olymp:3128 \
 && apk update && apk upgrade \
 && apk add --no-cache bash \
 && apk add --update npm \
 && mkdir /var/opt/simpleweb

COPY index.js /var/opt/simpleweb/
COPY package.json /var/opt/simpleweb/
WORKDIR /var/opt/simpleweb

RUN npm install

CMD ["npm", "start"]